# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "1.0.2"
  title: Signature Compare Module API
  
basePath: /SignatureComparisonModule/jaxrs

# Describe your paths here
paths:
  /getClientSignaturesList:
    get:
      responses:
        200:
          description: Ok
          schema:
            type: array
            items:
              type: string
        500:
          description: Couldn't connect to the database
  
  /getChecksList:
    get:
      responses:
        200:
          description: Ok
          schema:
            type: array
            items:
              type: string
        500:
          description: Couldn't connect to the database
  
  /getImage:
    get:
      parameters:
      -
        name: type
        in: query
        description: Type of image. (client's signature or check)
        required: true
        type: string
        enum:
          - client
          - check
      -
        name: name
        in: query
        description: Name of the image to be returned
        required: true
        type: string
      responses:
        200:
          description: Returns the requested image.
          schema:
            title: Base64 string
            type: array
            items:
              type: string
        500:
          description: Invalid **type** passed. Type must be either *client* or *check*.
        501:
          description: Image missing from database.
    
  /compare:
    get:
      parameters:
      -
        name: clientSignatureImageName
        in: query
        description: Name of the client's signature image
        required: true
        type: string
      -
        name: checkImageName
        in: query
        description: Name of the check's image
        required: true
        type: string
      
      responses:
        200:
          description: Comparison was successful. The comparison score is returned.
          schema:
            type: integer
            format: int32
        500:
          description: Comparison failed.